version: '3.8'

services:
  pg:
    restart: unless-stopped
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-network

  nest:
    restart: unless-stopped
    depends_on:
      - pg
    image: xalvaine/booking-backend:${VERSION}
    env_file:
      - .env
    environment:
      - NEST_PORT=80
      - NEST_ADDRESS=0.0.0.0
    volumes:
      - nest_node_modules:/home/app/node_modules
    working_dir: /home/app
    command: yarn start:prod
    networks:
      - app-network

  nginx:
    restart: unless-stopped
    image: nginx:1.21-alpine-perl
    depends_on:
      - nest
    environment:
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./dhparam:/etc/ssl/certs
    ports:
      - '80:80'
      - '443:443'

    networks:
      - app-network

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      - web-root:/var/www/html
      - ./dhparam:/etc/ssl/certs
    command: certonly --webroot -w /var/www/html -d ${SERVER_NAME} --non-interactive --agree-tos --register-unsafely-without-email ${STAGING}

volumes:
  pg:
  pgadmin:
  nest_node_modules:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:

networks:
  app-network:
