version: '3.8'

services:
  pg:
    restart: always
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin

  nest:
    restart: always
    depends_on:
      - pg
    build:
      context: .
    environment:
      - NEST_PORT=80
      - NEST_ADDRESS=0.0.0.0
    expose:
      - 8000
    volumes:
      - nest_node_modules:/home/app/node_modules
    working_dir: /home/app
    command: yarn start:prod

  nginx:
    restart: always
    image: nginx:stable
    depends_on:
      - nest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

volumes:
  pg:
  pgadmin:
  nest_node_modules:
